# Generated by Django 6.0 on 2026-07-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysession',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studysession',
            name='last_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
