# Generated by Django 6.0.7 on 2026-07-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_project_projectfile_projectsummary_textdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='audit_pending',
            field=models.BooleanField(default=False),
        ),
    ]
